
// Rates
export const FETCH_RATES_PENDING = 'FETCH_RATES_PENDING'
export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS'
export const FETCH_RATES_FAIL = 'FETCH_RATES_FAIL'

// Notifications
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS'
